const items = [
  { title: "Scan for CV" },
  {
    title: "September 2020 - December 2020",
    cardTitle: "Trainee Web Development",
    cardSubtitle: "neue fische GmbH - School & Pool for digital Talents",
    cardDetailedText: [
      "The possibility to shape my digital environment has appealed to me for a long time.",
      "In 2020 I followed my inner call for this career change.",
      "Experience:",
      "-Intense Coding Bootcamp of 3 month",
      "-Weekly Group projects",
      "-Pair Programming",
      "-540 hours of practical programming experience with self development of a Web App as a final project",
    ],
  },
  {
    title: "September 2018 – August 2020",
    cardTitle: "Visual Merchandise Coordinator & Trainer",
    cardSubtitle: `beeline GmbH`,
    cardDetailedText: [
      "The beeline GmbH is Germanies biggest fashion jewellery retailer located in Cologne.",
      "I worked for the Franchise department which made my position an international one. I traveled around the globe to train our partners and ensured via digital media the succsessful implementaion of guidelines as well as coaching.",
      "Workexperience:",
      "-Strategic and operational support for franchise Partner in visual merchandise and marketing issues",
      "-Creation, visualization and optimization of internal and external processes",
      "-Analysis of performance & assortment KPIs",
      "-Interface between franchise team, franchise partner, marketing department and conceptual visual merchandising",
      "-Implementation of visual merchandise trainings of franchise partner in Germany and abroad",
      "-Conceptual work",
    ],
  },
  {
    title: "Januar 2015 – August 2018",
    cardTitle: "Senior Assistant Store Manager",
    cardSubtitle: `OFFICE London LDT`,
    cardDetailedText: [
      "Office Holdings Ltd is a british foot- and streetware company. I supported the managing of the German Flagshipstore with around 400 square meters and 30 employes.Since the 1920s, Hitler had seen Russia",
      "One of my other responsibilities was the trainig of staff for Germany.",
      "Workexperience:",
      "-Coordination of HR related topics",
      "-People Management",
      "-Customer Service related topics",
      "-Cash Management",
      "-Visual Merchandising",
      "-Stockroom Management",
    ],
  },
  {
    title: "Januar 2012 – Dezember 2014",
    cardTitle: "Assistant Store Manager / Store Manager",
    cardSubtitle: `adidas AG`,
    cardDetailedText: [
      "adidas is one of the biggest sport brands world wide. I had the pleasure to introduce a new brand (adidas NEO) and manage the 250 square meters of the German Flagshipstore located in Cologne.",
      "The store was more of a Botique and at that time I was responsible for around 3 employes.",
      "Workexperience:",
      "-Taking care of the whole range of customer service, including direct contact, complaints etc",
      "-Planning staff efficiently and control timekeeping",
      "-Recruitment, onboarding, training and development of the store and his members",
      "-Coordination of goods, delivery from stockroom to POS to ensure a maximal replenishment for the customers",
      "-Creating a inviting shopping environment through coordination and implementation of Visual Merchandise standards",
      "-Being a role model in customer service, increasing sales and the brand by using advanced sales approach",
    ],
  },
  {
    title: "Juni 2010 - Dezember 2011",
    cardTitle: "Sales Assistant / Assistant Store Manager",
    cardSubtitle: `Sixty Deutschland GmbH`,
    cardDetailedText: [
      "Sixty is an Italian Fashion brand. This was my very first Management Job.",
      "I was responsible for around 15 employes.",
      "Workexperience:",
      "-Taking care of the whole range of customer service, including direct contact, complaints etc",
      "-Planning staff efficiently and control timekeeping",
      "-Recruitment, onboarding, training and development of the store and his members",
      "-Coordination of goods, delivery from stockroom to POS to ensure a maximal replenishment for the customers",
      "-Creating a inviting shopping environment through coordination and implementation of Visual Merchandise standards",
      "-Being a role model in customer service, increasing sales and the brand by using advanced sales approach",
    ],
  },
  {
    title: "April 2006 – Mai 2010",
    cardTitle: "Servicestaff",
    cardSubtitle: `Constantin Kinobetriebe GmbH`,
    cardDetailedText: [
      "Colognes biggest cinema.",
      "Workexperience:",
      "-Customer Service",
    ],
  },
  {
    title: "2003 – 2006",
    cardTitle: "Trained retail salesman",
    cardSubtitle: `Vocational Training at Modehaus Z. Müller`,
  },
  {
    title: "2002 – 2003",
    cardTitle: "Upper secondary vocational college of commerce",
    cardSubtitle: `Theoretical preparation for vocational training at the Rastatt commercial college of commerce `,
  },
  {
    title: "1996 – 2001",
    cardTitle: "O-level",
    cardSubtitle: `Secondary school graduation at the Werner-von-Siemens secondary school`,
  },
];

export default items;
